import Mathlib.RingTheory.Ideal.Span
import Mathlib.Algebra.Polynomial.Derivative
import Mathlib.RingTheory.Polynomial.Basic

/-!
# Phase D1 — the unit-multiplication membership transfer

The norm identity (`norm_identity_elim`) needs the witness membership in the ideal generated by the
**monic Weierstrass factor** `h` and its derivative: `C(P) ∈ ⟨h, h'⟩`. Weierstrass preparation gives
`g = u · h` (with `u` a unit), so the witness — which lives in `⟨g, g'⟩` — must be pushed into
`⟨h, h'⟩`.

This file proves the **algebraic core** of that transfer, in any `CommRing`:

`C(P) ∈ ⟨u·h, (u·h)'⟩  ⟹  C(P) ∈ ⟨h, h'⟩`.

Remarkably the *forward* direction needs **no** hypothesis on `u`: both `u·h` and `(u·h)' = u'h + uh'`
already lie in `⟨h, h'⟩`, so `⟨u·h, (u·h)'⟩ ⊆ ⟨h, h'⟩` outright. (The unit hypothesis is only needed
for the reverse inclusion / ideal *equality*, which the transfer does not require.)

The remaining, genuinely hard part of D1 — obtaining the *input* membership for the
complexified/Weierstrass data from the real witness (whose Bézout cofactors are not analytic; this
needs subresultant theory, absent from Mathlib) — is tracked separately as the residual A3/D1
obstacle.
-/

open Polynomial

variable {R : Type*} [CommRing R]

/-- **D1 core.** If `p` lies in the ideal generated by `u·h` and its derivative, then it lies in the
ideal generated by `h` and `h'`. No assumption on `u` is needed for this inclusion. -/
theorem mem_span_pair_deriv_of_mul (u h p : R[X])
    (hp : p ∈ Ideal.span ({u * h, derivative (u * h)} : Set R[X])) :
    p ∈ Ideal.span ({h, derivative h} : Set R[X]) := by
  refine Ideal.span_le.mpr ?_ hp
  rw [Set.insert_subset_iff, Set.singleton_subset_iff]
  refine ⟨?_, ?_⟩
  · -- `u·h = u * h ∈ ⟨h⟩ ⊆ ⟨h, h'⟩`
    exact Ideal.mul_mem_left _ u (Ideal.subset_span (Set.mem_insert _ _))
  · -- `(u·h)' = u'·h + u·h' ∈ ⟨h, h'⟩`
    rw [derivative_mul]
    refine Ideal.add_mem _ ?_ ?_
    · exact Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert _ _))
    · exact Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert_of_mem _ rfl))

/-- The ideals `⟨u·h, (u·h)'⟩` and `⟨h, h'⟩` coincide when `u` is a unit: the previous inclusion plus
its reverse (`h = u⁻¹·(u·h)`, `h' = u⁻¹·((u·h)' − u'·h)`). This is the full ideal-equality form of
the Weierstrass transfer; the membership transfer above is the half actually used downstream. -/
theorem span_pair_deriv_mul_eq_of_isUnit (u h : R[X]) (hu : IsUnit u) :
    Ideal.span ({u * h, derivative (u * h)} : Set R[X])
      = Ideal.span ({h, derivative h} : Set R[X]) := by
  apply le_antisymm
  · rw [Ideal.span_le, Set.insert_subset_iff, Set.singleton_subset_iff]
    refine ⟨Ideal.mul_mem_left _ u (Ideal.subset_span (Set.mem_insert _ _)), ?_⟩
    rw [derivative_mul]
    exact Ideal.add_mem _
      (Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert _ _)))
      (Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert_of_mem _ rfl)))
  · obtain ⟨v, hv⟩ := hu
    set w : R[X] := ↑v⁻¹ with hw
    have hwu : w * u = 1 := by rw [hw, ← hv]; exact v.inv_mul
    rw [Ideal.span_le, Set.insert_subset_iff, Set.singleton_subset_iff]
    have huh : u * h ∈ Ideal.span ({u * h, derivative (u * h)} : Set R[X]) :=
      Ideal.subset_span (Set.mem_insert _ _)
    have hduh : derivative (u * h) ∈ Ideal.span ({u * h, derivative (u * h)} : Set R[X]) :=
      Ideal.subset_span (Set.mem_insert_of_mem _ rfl)
    constructor
    · -- `h = w · (u·h)` since `w·u = 1`
      have hm := Ideal.mul_mem_left
        (Ideal.span ({u * h, derivative (u * h)} : Set R[X])) w huh
      rwa [← mul_assoc, hwu, one_mul] at hm
    · -- `h' = w·(u·h)' − w·u'·h`, and both summands are in the span
      have hb : w * (derivative u * h)
          ∈ Ideal.span ({u * h, derivative (u * h)} : Set R[X]) := by
        have hm := Ideal.mul_mem_left
          (Ideal.span ({u * h, derivative (u * h)} : Set R[X])) (w * derivative u * w) huh
        have hvuh : (w * derivative u * w) * (u * h) = w * (derivative u * h) := by
          calc (w * derivative u * w) * (u * h)
              = derivative u * (w * u) * (w * h) := by ring
            _ = derivative u * 1 * (w * h) := by rw [hwu]
            _ = w * (derivative u * h) := by ring
        rwa [hvuh] at hm
      have hm2 := Ideal.mul_mem_left
        (Ideal.span ({u * h, derivative (u * h)} : Set R[X])) w hduh
      have hfin := Ideal.sub_mem _ hm2 hb
      have heq2 : w * derivative (u * h) - w * (derivative u * h) = derivative h := by
        rw [derivative_mul]
        have hr : w * (derivative u * h + u * derivative h) - w * (derivative u * h)
            = (w * u) * derivative h := by ring
        rw [hr, hwu, one_mul]
      rwa [heq2] at hfin
