import Mathlib
import Mccalum.Basic
import Mccalum.DiscrMul
import Mccalum.Brown.Transfer

/-!
# Discriminant facts for Brown's theorem

Two classical facts, neither in Mathlib, needed to recover Brown's original
Theorem 3.1 from the generalized `brown_generalized` with witness `P = disc f`:

* **Fact A** (`discr_mem_span`): `C (disc f) ∈ ⟨f, f'⟩` for `f` of degree `≥ 2`
  with `natDegree f` invertible.  The resultant only gives `lc · disc ∈ ⟨f, f'⟩`;
  to remove the `lc` factor we use the polar polynomial `g = n·f - X·f'` and the
  identity `lc(f') · Res(f', g) = n^{n-1} · Res(f', f)` (pure resultant calculus),
  cancelling `n · lc` in the domain.

* **Lemma 8.1** (`discr_reverse`): `disc (reverse f) = disc f` when the constant
  coefficient of `f` is nonzero.
-/

noncomputable section

open Polynomial

namespace Brown

variable {R : Type*} [CommRing R] [IsDomain R]

/-! ### Fact A: the discriminant lies in `⟨f, f'⟩` -/

/-- **Fact A.**  For `f` of degree `≥ 2` with `natDegree f` invertible in the
domain `R`, the discriminant lies in the ideal generated by `f` and `f'`. -/
theorem discr_mem_span (f : R[X])
    (hdeg : 2 ≤ f.natDegree) (hn : IsUnit (f.natDegree : R)) :
    C f.discr ∈ Ideal.span ({f, derivative f} : Set R[X]) := by
  have hf_ne : f ≠ 0 := ne_zero_of_natDegree_gt (by omega : 0 < f.natDegree)
  have hlc_ne : f.leadingCoeff ≠ 0 := leadingCoeff_ne_zero.mpr hf_ne
  have hn_ne : (f.natDegree : R) ≠ 0 := hn.ne_zero
  have hf'_deg : (derivative f).natDegree ≤ f.natDegree - 1 := natDegree_derivative_le f
  -- the polar polynomial `g = n·f - X·f'`
  set g : R[X] := C (f.natDegree : R) * f - X * derivative f with hg_def
  -- `f'.coeff (n-1) = n · lc`
  have hlcf' : (derivative f).coeff (f.natDegree - 1) = (f.natDegree : R) * f.leadingCoeff := by
    rw [coeff_derivative, show f.natDegree - 1 + 1 = f.natDegree from by omega, coeff_natDegree,
      Nat.cast_sub (show 1 ≤ f.natDegree from by omega)]
    ring
  -- `g` has degree `≤ n-1`
  have hg_deg : g.natDegree ≤ f.natDegree - 1 := by
    rw [Polynomial.natDegree_le_iff_coeff_eq_zero]
    intro m hm
    rw [hg_def, coeff_sub, coeff_C_mul]
    obtain ⟨m', rfl⟩ : ∃ m', m = m' + 1 := ⟨m - 1, by omega⟩
    rw [coeff_X_mul]
    by_cases hmn1 : m' + 1 = f.natDegree
    · rw [hmn1, coeff_natDegree, show m' = f.natDegree - 1 from by omega, hlcf']
      ring
    · have h1 : f.coeff (m' + 1) = 0 := coeff_eq_zero_of_natDegree_lt (by omega)
      have h2 : (derivative f).coeff m' = 0 := coeff_eq_zero_of_natDegree_lt (by omega)
      rw [h1, h2]; ring
  -- (A): `Res(f', g, n-1, n) = n^{n-1} · Res(f', f, n-1, n)`
  have hgform : g = C (f.natDegree : R) * f + derivative f * (-X) := by rw [hg_def]; ring
  have hA : resultant (derivative f) g (f.natDegree - 1) f.natDegree
      = (f.natDegree : R) ^ (f.natDegree - 1) *
        resultant (derivative f) f (f.natDegree - 1) f.natDegree := by
    rw [hgform,
      resultant_add_mul_right (derivative f) (C (f.natDegree : R) * f) (-X)
        (f.natDegree - 1) f.natDegree
        (by simpa using (by omega : 1 + (f.natDegree - 1) ≤ f.natDegree)) hf'_deg,
      resultant_C_mul_right (derivative f) f (f.natDegree - 1) f.natDegree (f.natDegree : R)]
  -- (B): `Res(f', g, n-1, n) = f'.coeff(n-1) · Res(f', g, n-1, n-1)`
  have hB : resultant (derivative f) g (f.natDegree - 1) f.natDegree
      = (derivative f).coeff (f.natDegree - 1) *
        resultant (derivative f) g (f.natDegree - 1) (f.natDegree - 1) := by
    have h := resultant_add_right_deg (derivative f) g (f.natDegree - 1) (f.natDegree - 1) 1 hg_deg
    rwa [show f.natDegree - 1 + 1 = f.natDegree from by omega, pow_one] at h
  -- combine and reduce to disc
  have hpos : (0 : WithBot ℕ) < f.degree :=
    natDegree_pos_iff_degree_pos.mp (by omega)
  have hcomm : resultant (derivative f) f (f.natDegree - 1) f.natDegree
      = (-1) ^ ((f.natDegree - 1) * f.natDegree) *
        resultant f (derivative f) f.natDegree (f.natDegree - 1) :=
    resultant_comm (derivative f) f (f.natDegree - 1) f.natDegree
  have hderiv := resultant_deriv hpos
  set R0 : R := resultant (derivative f) g (f.natDegree - 1) (f.natDegree - 1) with hR0_def
  -- the unit factor
  set s : R := (-1) ^ ((f.natDegree - 1) * f.natDegree) *
    (-1) ^ (f.natDegree * (f.natDegree - 1) / 2) with hs_def
  have hs : IsUnit s := by
    rw [hs_def]
    exact ((isUnit_one.neg).pow _).mul ((isUnit_one.neg).pow _)
  -- key scalar equation: `n · lc · R0 = n^{n-1} · s · lc · disc`
  have key : (f.natDegree : R) * f.leadingCoeff * R0
      = (f.natDegree : R) ^ (f.natDegree - 1) * s * f.leadingCoeff * f.discr := by
    have e := hB.symm.trans hA
    rw [hlcf', hR0_def] at e
    rw [hcomm, hderiv] at e
    rw [hs_def]
    linear_combination e
  -- cancel `n · lc`
  have hpow : (f.natDegree : R) ^ (f.natDegree - 1)
      = (f.natDegree : R) * (f.natDegree : R) ^ (f.natDegree - 2) := by
    conv_lhs => rw [show f.natDegree - 1 = (f.natDegree - 2) + 1 from by omega]
    rw [pow_succ']
  have hne : (f.natDegree : R) * f.leadingCoeff ≠ 0 := mul_ne_zero hn_ne hlc_ne
  have hR0 : R0 = (f.natDegree : R) ^ (f.natDegree - 2) * s * f.discr := by
    apply mul_left_cancel₀ hne
    rw [key, hpow]; ring
  -- membership: `C R0 ∈ ⟨f', g⟩ ⊆ ⟨f, f'⟩`
  obtain ⟨p, q, _, _, hbez⟩ := exists_mul_add_mul_eq_C_resultant (m := f.natDegree - 1)
    (n := f.natDegree - 1) (derivative f) g hf'_deg hg_deg (Or.inl (by omega))
  rw [← hR0_def] at hbez
  have hmem_fg' : C R0 ∈ Ideal.span ({derivative f, g} : Set R[X]) :=
    Ideal.mem_span_pair.mpr ⟨p, q, by rw [mul_comm p (derivative f), mul_comm q g]; exact hbez⟩
  have hsub : Ideal.span ({derivative f, g} : Set R[X]) ≤
      Ideal.span ({f, derivative f} : Set R[X]) := by
    rw [Ideal.span_le]
    intro x hx
    rcases hx with rfl | hx
    · exact Ideal.subset_span (Set.mem_insert_of_mem _ rfl)
    · rw [Set.mem_singleton_iff] at hx
      subst hx
      rw [hg_def]
      exact sub_mem
        (Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert _ _)))
        (Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert_of_mem _ rfl)))
  have hCR0 : C R0 ∈ Ideal.span ({f, derivative f} : Set R[X]) := hsub hmem_fg'
  -- divide by the unit `C (n^{n-2} · s)`
  have hu : IsUnit (C ((f.natDegree : R) ^ (f.natDegree - 2) * s) : R[X]) :=
    isUnit_C.mpr ((hn.pow _).mul hs)
  obtain ⟨u, hu_eq⟩ := hu
  have hCR0_eq : C R0 = (u : R[X]) * C f.discr := by
    rw [hR0, hu_eq, ← map_mul]
  have : C f.discr = (↑u⁻¹ : R[X]) * C R0 := by
    rw [hCR0_eq, ← mul_assoc, Units.inv_mul, one_mul]
  rw [this]
  exact Ideal.mul_mem_left _ _ hCR0

/-! ### Sign of the reversal permutation -/

open Equiv in
/-- The sign of the order-reversing permutation of `Fin N` is `(-1)^{N(N-1)/2}`. -/
theorem sign_revPerm {N : ℕ} :
    Equiv.Perm.sign (Fin.revPerm : Equiv.Perm (Fin N)) = (-1) ^ (N * (N - 1) / 2) := by
  rw [Equiv.Perm.sign_eq_prod_prod_Ioi]
  have hterm : ∀ i : Fin N, ∀ j ∈ Finset.Ioi i,
      (if Fin.revPerm i < Fin.revPerm j then (1 : ℤˣ) else -1) = -1 := by
    intro i j hj
    rw [Finset.mem_Ioi] at hj
    refine if_neg ?_
    simp only [Fin.revPerm_apply]
    rw [Fin.rev_lt_rev]
    exact not_lt.mpr hj.le
  rw [Finset.prod_congr rfl fun i _ => Finset.prod_congr rfl (hterm i)]
  simp_rw [Finset.prod_const]
  rw [Finset.prod_pow_eq_pow_sum]
  congr 1
  simp_rw [Fin.card_Ioi]
  rw [Fin.sum_univ_eq_sum_range (fun i => N - 1 - i) N,
    Finset.sum_range_reflect (fun i => i) N]
  exact Finset.sum_range_id N

/-! ### Resultant of reflections -/

open Equiv in
omit [IsDomain R] in
/-- **Reflection–resultant identity.**  Reflecting both polynomials at the formal
degrees `a` and `b` multiplies the resultant by `(-1)^{ab}`.  Proved by reversing
the rows (full reversal of `Fin (a+b)`) and the columns (block-wise reversal) of the
Sylvester matrix. -/
theorem resultant_reflect (F G : R[X]) (a b : ℕ) :
    resultant (reflect a F) (reflect b G) a b = (-1) ^ (a * b) * resultant F G a b := by
  classical
  -- the column-reversal permutation (block-wise reverse)
  set σ : Equiv.Perm (Fin (a + b)) :=
    finSumFinEquiv.permCongr (Equiv.sumCongr Fin.revPerm Fin.revPerm) with hσ_def
  have hσl : ∀ j₁ : Fin a, σ (Fin.castAdd b j₁) = Fin.castAdd b j₁.rev := by
    intro j₁
    rw [hσ_def, Equiv.permCongr_apply]
    simp [finSumFinEquiv_symm_apply_castAdd]
  have hσr : ∀ j₁ : Fin b, σ (Fin.natAdd a j₁) = Fin.natAdd a j₁.rev := by
    intro j₁
    rw [hσ_def, Equiv.permCongr_apply]
    simp [finSumFinEquiv_symm_apply_natAdd]
  -- the Sylvester matrix of the reflections is a reindexing of the original
  have hmat : sylvester (reflect a F) (reflect b G) a b
      = (sylvester F G a b).submatrix (⇑(Fin.revPerm)) (⇑σ) := by
    ext i j
    have hi : (i : ℕ) < a + b := i.isLt
    induction j using Fin.addCases with
    | left j₁ =>
      have hj : (j₁ : ℕ) < a := j₁.isLt
      simp only [sylvester, Matrix.of_apply, Matrix.submatrix_apply, Fin.addCases_left, hσl j₁,
        Fin.revPerm_apply, Fin.val_rev, Set.mem_Icc]
      by_cases hc : (j₁ : ℕ) ≤ (i : ℕ) ∧ (i : ℕ) ≤ (j₁ : ℕ) + b
      · rw [if_pos hc, if_pos (by omega), coeff_reflect, revAt_le (by omega)]
        congr 1
        omega
      · rw [if_neg hc, if_neg (by omega)]
    | right j₁ =>
      have hj : (j₁ : ℕ) < b := j₁.isLt
      simp only [sylvester, Matrix.of_apply, Matrix.submatrix_apply, Fin.addCases_right, hσr j₁,
        Fin.revPerm_apply, Fin.val_rev, Set.mem_Icc]
      by_cases hc : (j₁ : ℕ) ≤ (i : ℕ) ∧ (i : ℕ) ≤ (j₁ : ℕ) + a
      · rw [if_pos hc, if_pos (by omega), coeff_reflect, revAt_le (by omega)]
        congr 1
        omega
      · rw [if_neg hc, if_neg (by omega)]
  -- take determinants
  rw [resultant, resultant, hmat,
    show (sylvester F G a b).submatrix (⇑(Fin.revPerm)) (⇑σ)
        = ((sylvester F G a b).submatrix (⇑(Fin.revPerm)) id).submatrix id (⇑σ) from rfl,
    Matrix.det_permute', Matrix.det_permute]
  -- compute the two signs
  have hsignσ : Equiv.Perm.sign σ
      = (-1) ^ (a * (a - 1) / 2) * (-1) ^ (b * (b - 1) / 2) := by
    rw [hσ_def, Equiv.Perm.sign_permCongr, Equiv.Perm.sign_sumCongr, sign_revPerm, sign_revPerm]
  rw [← mul_assoc, sign_revPerm, hsignσ]
  congr 1
  -- reduce to the exponent identity
  have hr : (a + b) * (a + b - 1) / 2 = a * (a - 1) / 2 + a * b + b * (b - 1) / 2 :=
    (sign_exponent_identity a b).symm
  push_cast
  rw [hr]
  generalize a * (a - 1) / 2 = p
  generalize b * (b - 1) / 2 = q
  have e1 : (-1 : R) ^ p * (-1) ^ p = 1 := by rw [← pow_add]; exact Even.neg_one_pow ⟨p, rfl⟩
  have e2 : (-1 : R) ^ q * (-1) ^ q = 1 := by rw [← pow_add]; exact Even.neg_one_pow ⟨q, rfl⟩
  rw [pow_add, pow_add]
  calc (-1 : R) ^ p * (-1) ^ q * ((-1) ^ p * (-1) ^ (a * b) * (-1) ^ q)
      = ((-1) ^ p * (-1) ^ p) * ((-1) ^ q * (-1) ^ q) * (-1) ^ (a * b) := by ring
    _ = (-1) ^ (a * b) := by rw [e1, e2, one_mul, one_mul]

/-! ### Lemma 8.1: discriminant of the reverse -/

/-- **Brown's Lemma 8.1.**  If `f` has nonzero constant coefficient, then the
discriminant of its (degree-`n`) reverse equals the discriminant of `f`. -/
theorem discr_reverse [CharZero R] (f : R[X]) (h0 : f.coeff 0 ≠ 0) :
    f.reverse.discr = f.discr := by
  rcases Nat.eq_zero_or_pos f.natDegree with hn0 | hpos_n
  · obtain ⟨c, rfl⟩ := natDegree_eq_zero.mp hn0
    rw [Polynomial.reverse_C]
  -- abbreviations and basic facts about `f` and `reverse f`
  have hf_ne : f ≠ 0 := fun h => h0 (by rw [h, coeff_zero])
  have hlc_ne : f.leadingCoeff ≠ 0 := leadingCoeff_ne_zero.mpr hf_ne
  have hrev_eq : f.reverse = reflect f.natDegree f := rfl
  have hntd : f.natTrailingDegree = 0 :=
    le_antisymm (natTrailingDegree_le_of_ne_zero h0) (Nat.zero_le _)
  have hrevdeg : f.reverse.natDegree = f.natDegree := by
    rw [Polynomial.reverse_natDegree, hntd, Nat.sub_zero]
  have hrev_lc : f.reverse.leadingCoeff = f.coeff 0 := by
    rw [Polynomial.reverse_leadingCoeff, Polynomial.trailingCoeff, hntd]
  have hrev_c0 : f.reverse.coeff 0 = f.leadingCoeff := coeff_zero_reverse f
  have hrev_cn : f.reverse.coeff f.natDegree = f.coeff 0 := by
    rw [hrev_eq, coeff_reflect, revAt_le (le_refl _), Nat.sub_self]
  have hrev_le : f.reverse.natDegree ≤ f.natDegree := hrevdeg.le
  have hrevderiv_deg : f.reverse.derivative.natDegree = f.natDegree - 1 := by
    rw [natDegree_derivative_charZero (by rw [hrevdeg]; exact hpos_n), hrevdeg]
  have hreflectf'_le : (reflect (f.natDegree - 1) (derivative f)).natDegree ≤ f.natDegree - 1 :=
    natDegree_reflect_le.trans (max_le le_rfl (by have := natDegree_derivative_le f; omega))
  -- Euler identity: `reflect (n-1) f' = C n · rev f - X · (rev f)'`
  have hEuler : reflect (f.natDegree - 1) (derivative f)
      = C ((f.natDegree : ℕ) : R) * f.reverse - X * f.reverse.derivative := by
    have h := reflect_derivative_eq f (f.natDegree - 1) (by omega)
    rw [show f.natDegree - 1 + 1 = f.natDegree from by omega, ← hrev_eq] at h
    exact h
  -- (III) reflection–resultant
  have hIII : resultant f.reverse (reflect (f.natDegree - 1) (derivative f))
        f.natDegree (f.natDegree - 1)
      = (-1) ^ (f.natDegree * (f.natDegree - 1)) *
        resultant f (derivative f) f.natDegree (f.natDegree - 1) := by
    rw [hrev_eq]; exact resultant_reflect f (derivative f) f.natDegree (f.natDegree - 1)
  -- (IV) pad the second formal degree
  have hIV : resultant f.reverse (reflect (f.natDegree - 1) (derivative f)) f.natDegree f.natDegree
      = f.coeff 0 *
        resultant f.reverse (reflect (f.natDegree - 1) (derivative f)) f.natDegree (f.natDegree - 1) := by
    have h := resultant_add_right_deg f.reverse (reflect (f.natDegree - 1) (derivative f))
      f.natDegree (f.natDegree - 1) 1 hreflectf'_le
    rwa [show f.natDegree - 1 + 1 = f.natDegree from by omega, pow_one, hrev_cn] at h
  -- (Ia) Euler substitution inside `Res(rev f, X·(rev f)', n, n)`
  have hIa : resultant f.reverse (X * f.reverse.derivative) f.natDegree f.natDegree
      = (-1) ^ f.natDegree *
        resultant f.reverse (reflect (f.natDegree - 1) (derivative f)) f.natDegree f.natDegree := by
    have hXd : X * f.reverse.derivative
        = (- reflect (f.natDegree - 1) (derivative f)) + f.reverse * C ((f.natDegree : ℕ) : R) := by
      rw [hEuler]; ring
    rw [hXd, resultant_add_mul_right f.reverse (- reflect (f.natDegree - 1) (derivative f))
        (C ((f.natDegree : ℕ) : R)) f.natDegree f.natDegree (by rw [natDegree_C]; omega) hrev_le,
      show (- reflect (f.natDegree - 1) (derivative f))
          = C (-1 : R) * reflect (f.natDegree - 1) (derivative f) from by
            rw [map_neg, map_one, neg_one_mul],
      resultant_C_mul_right]
  -- (Ib) split off the factor `X`
  have hIb : resultant f.reverse (X * f.reverse.derivative) f.natDegree f.natDegree
      = (-1) ^ f.natDegree * f.leadingCoeff *
        resultant f.reverse f.reverse.derivative f.natDegree (f.natDegree - 1) := by
    have h := resultant_mul_right f.reverse X f.reverse.derivative f.natDegree hrev_le
    rw [natDegree_X, hrevderiv_deg, show 1 + (f.natDegree - 1) = f.natDegree from by omega] at h
    have hX : f.reverse.resultant X f.natDegree 1 = (-1) ^ f.natDegree * f.leadingCoeff := by
      have hh := resultant_X_pow_right f.reverse f.natDegree 1 hrev_le
      rw [pow_one, pow_one, mul_one, hrev_c0] at hh
      exact hh
    rw [h, hX]
  -- (★) combine: `lc · Res(rev f,(rev f)') = a₀ · Res(f,f')`
  have hstar : f.leadingCoeff * resultant f.reverse f.reverse.derivative f.natDegree (f.natDegree - 1)
      = f.coeff 0 * resultant f (derivative f) f.natDegree (f.natDegree - 1) := by
    have hpow_one : ((-1 : R)) ^ (f.natDegree * (f.natDegree - 1)) = 1 := by
      apply Even.neg_one_pow
      rcases Nat.even_or_odd f.natDegree with he | ho
      · exact he.mul_right _
      · exact (Nat.Odd.sub_odd ho odd_one).mul_left _
    have hcancel : (-1 : R) ^ f.natDegree *
          (f.leadingCoeff * resultant f.reverse f.reverse.derivative f.natDegree (f.natDegree - 1))
        = (-1 : R) ^ f.natDegree *
          (f.coeff 0 * resultant f (derivative f) f.natDegree (f.natDegree - 1)) := by
      rw [← mul_assoc, ← hIb, hIa, hIV, hIII, hpow_one]; ring
    exact mul_left_cancel₀ (pow_ne_zero _ (by norm_num)) hcancel
  -- convert both resultants to discriminants
  have hpos_f : (0 : WithBot ℕ) < f.degree := natDegree_pos_iff_degree_pos.mp hpos_n
  have hpos_rev : (0 : WithBot ℕ) < f.reverse.degree :=
    natDegree_pos_iff_degree_pos.mp (by rw [hrevdeg]; exact hpos_n)
  have hderiv_f := resultant_deriv hpos_f
  have hderiv_rev := resultant_deriv hpos_rev
  rw [hrevdeg, hrev_lc] at hderiv_rev
  rw [hderiv_rev, hderiv_f] at hstar
  -- cancel the common nonzero factor
  have hkey : (f.leadingCoeff * f.coeff 0 * (-1) ^ (f.natDegree * (f.natDegree - 1) / 2)) * f.reverse.discr
      = (f.leadingCoeff * f.coeff 0 * (-1) ^ (f.natDegree * (f.natDegree - 1) / 2)) * f.discr := by
    linear_combination hstar
  exact mul_left_cancel₀
    (mul_ne_zero (mul_ne_zero hlc_ne h0) (pow_ne_zero _ (by norm_num))) hkey

/-- The discriminant of `f` lies in the ideal generated by `reverse f` and its
derivative, provided `f` has degree `≥ 2`, nonzero constant coefficient, and
`natDegree f` invertible.  Combines Fact A on `reverse f` with Lemma 8.1. -/
theorem discr_mem_span_reverse [CharZero R] (g : R[X])
    (hg2 : 2 ≤ g.natDegree) (h0 : g.coeff 0 ≠ 0) (hn : IsUnit (g.natDegree : R)) :
    C g.discr ∈ Ideal.span ({g.reverse, derivative g.reverse} : Set R[X]) := by
  have hrevdeg : g.reverse.natDegree = g.natDegree := by
    rw [Polynomial.reverse_natDegree,
      le_antisymm (natTrailingDegree_le_of_ne_zero h0) (Nat.zero_le _), Nat.sub_zero]
  rw [← discr_reverse g h0]
  exact discr_mem_span g.reverse (by rw [hrevdeg]; exact hg2) (by rw [hrevdeg]; exact hn)

end Brown

